### PR TITLE
add homepage

### PR DESCRIPTION
**Pull request by iRohitGaur**
homepage

Files to ignore:
- All CSS files (already checked during HTML phase)
- Icons.jsx
- Data files

Files to check:
- components
- Homepage.jsx

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
The code looks good to me. The preview link deployed by netlify isn't working please check that. Good work. Good to merge.

**Comment by iRohitGaur** [comment]
> The code looks good to me. The preview link deployed by netlify isn't working please check that. Good work. Good to merge.

@zoef-yt Thanks! Yes actually this repo is also submitted for submission review.

**Review by bhtibrewal — APPROVED** [review]
looks good merge, just a suggestion make smaller PRs, would be good for reviews

**Comment by iRohitGaur** [comment]
> looks good merge, just a suggestion make smaller PRs, would be good for reviews

@bhtibrewal Thanks! Sure. Yes, build and many extra files get added every time 😁

**Pull request merged**
